// ─────────────────────────────────────────────────────────────
// generador_playlists_cue_nfo.dart — PART de generador_playlists.dart:
// generación de los archivos CUE (hoja de índice con PERFORMER,
// TRACK, ISRC e INDEX por pista, agrupando por disco) y NFO (ficha
// de metadatos con fecha, álbum, artista, género y el listado de
// pistas con duración). Ambos escriben en config.outputDir y
// devuelven la ruta generada.
// Se conecta con: generador_playlists.dart (misma library).
// Parte del flujo: playlists (exportar a archivos).
// ─────────────────────────────────────────────────────────────

part of 'generador_playlists.dart';

/// Genera una hoja CUE. Devuelve la ruta; lanza si falla.
Future<String> generarCUE(ConfigPlaylist config) async {
  if (config.tracks.isEmpty) {
    throw ArgumentError('no tracks for CUE');
  }

  final performer =
      config.artist.isNotEmpty ? config.artist : config.tracks[0].artist;
  final title =
      config.name.isNotEmpty ? config.name : 'Unknown Album';

  final b = StringBuffer()
    ..writeln('REM GENRE ${config.genre}')
    ..writeln('REM DATE ${config.year}')
    ..writeln('PERFORMER "$performer"')
    ..writeln('TITLE "$title"')
    ..writeln('FILE "dummy.flac" FLAC');

  var currentDisc = 0;
  for (var i = 0; i < config.tracks.length; i++) {
    final t = config.tracks[i];
    if (t.discNum > 0 && t.discNum != currentDisc) {
      if (currentDisc > 0) {
        b.writeln('  REM END_DISC');
      }
      currentDisc = t.discNum;
    }

    var idx = i + 1;
    if (t.trackNum > 0) {
      idx = t.trackNum;
    }
    b.writeln('  TRACK ${idx.toString().padLeft(2, '0')} AUDIO');
    b.writeln('    TITLE "${t.title}"');
    b.writeln('    PERFORMER "${t.artist}"');
    if (t.isrc.isNotEmpty) {
      b.writeln('    ISRC ${t.isrc}');
    }
    b.writeln('    INDEX 01 00:00:00');
  }

  final filename = '${GeneradorPlaylists.sanitizar(config.name)}.cue';
  final outputPath = '${config.outputDir}${Platform.pathSeparator}$filename';
  await File(outputPath).writeAsString(b.toString());
  return outputPath;
}

/// Genera un archivo NFO. Devuelve la ruta; lanza si falla.
Future<String> generarNFO(ConfigPlaylist config) async {
  final now = DateTime.now();
  final date = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';
  final time =
      '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:${now.second.toString().padLeft(2, '0')}';
  final b = StringBuffer()
    ..writeln('Generated by Bitly')
    ..writeln('Date: $date $time')
    ..writeln('Album: ${config.name}')
    ..writeln('Artist: ${config.artist}')
    ..writeln('Genre: ${config.genre}')
    ..writeln('Year: ${config.year}')
    ..writeln('Tracks: ${config.tracks.length}')
    ..writeln()
    ..writeln('--- Track Listing ---');

  for (var i = 0; i < config.tracks.length; i++) {
    final t = config.tracks[i];
    final dur = GeneradorPlaylists.formatearDuracion(t.durationMs ~/ 1000);
    b.writeln(
        '${(i + 1).toString().padLeft(2, '0')}. ${t.artist} - ${t.title} [$dur]');
  }

  final filename = '${GeneradorPlaylists.sanitizar(config.name)}.nfo';
  final outputPath = '${config.outputDir}${Platform.pathSeparator}$filename';
  await File(outputPath).writeAsString(b.toString());
  return outputPath;
}