package gobackend

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type PlaylistTrack struct {
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Album      string `json:"album"`
	Duration   int    `json:"duration_ms"`
	FilePath   string `json:"file_path"`
	TrackNum   int    `json:"track_number"`
	DiscNum    int    `json:"disc_number"`
	ISRC       string `json:"isrc"`
}

type PlaylistConfig struct {
	Name       string
	Artist     string
	Year       string
	Genre      string
	Tracks     []PlaylistTrack
	OutputDir  string
}

func GenerateM3U(config PlaylistConfig) (string, error) {
	if len(config.Tracks) == 0 {
		return "", fmt.Errorf("no tracks for M3U")
	}

	var b strings.Builder
	b.WriteString("#EXTM3U\n")
	b.WriteString(fmt.Sprintf("#PLAYLIST: %s\n", config.Name))
	b.WriteString(fmt.Sprintf("#GENRE: %s\n", config.Genre))
	b.WriteString(fmt.Sprintf("#DATE: %s\n", config.Year))
	b.WriteString("\n")

	for _, t := range config.Tracks {
		extinf := fmt.Sprintf("#EXTINF:%d,%s - %s\n",
			t.Duration/1000, t.Artist, t.Title)
		b.WriteString(extinf)
		relPath := t.FilePath
		if absPath, err := filepath.Abs(t.FilePath); err == nil {
			relPath = absPath
		}
		b.WriteString(relPath)
		b.WriteString("\n")
	}

	filename := sanitizeFilename(config.Name) + ".m3u"
	outputPath := filepath.Join(config.OutputDir, filename)
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("write M3U: %w", err)
	}
	return outputPath, nil
}

func GenerateM3U8(config PlaylistConfig) (string, error) {
	if len(config.Tracks) == 0 {
		return "", fmt.Errorf("no tracks for M3U8")
	}

	var b strings.Builder
	b.WriteString("#EXTM3U\n")
	b.WriteString("#PLAYLIST: " + config.Name + "\n")

	for _, t := range config.Tracks {
		b.WriteString(fmt.Sprintf("#EXTINF:%d,%s - %s\n", t.Duration/1000, t.Artist, t.Title))
		relPath := t.FilePath
		if absPath, err := filepath.Abs(t.FilePath); err == nil {
			relPath = absPath
		}
		b.WriteString(relPath + "\n")
	}

	filename := sanitizeFilename(config.Name) + ".m3u8"
	outputPath := filepath.Join(config.OutputDir, filename)
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("write M3U8: %w", err)
	}
	return outputPath, nil
}

func GenerateCUE(config PlaylistConfig) (string, error) {
	if len(config.Tracks) == 0 {
		return "", fmt.Errorf("no tracks for CUE")
	}

	var b strings.Builder
	performer := config.Artist
	if performer == "" {
		performer = config.Tracks[0].Artist
	}
	title := config.Name
	if title == "" {
		title = "Unknown Album"
	}

	b.WriteString(fmt.Sprintf("REM GENRE %s\n", config.Genre))
	b.WriteString(fmt.Sprintf("REM DATE %s\n", config.Year))
	b.WriteString(fmt.Sprintf("PERFORMER %q\n", performer))
	b.WriteString(fmt.Sprintf("TITLE %q\n", title))
	b.WriteString("FILE \"dummy.flac\" FLAC\n")

	currentDisc := 0
	for i, t := range config.Tracks {
		if t.DiscNum > 0 && t.DiscNum != currentDisc {
			if currentDisc > 0 {
				b.WriteString("  REM END_DISC\n")
			}
			currentDisc = t.DiscNum
		}

		idx := i + 1
		if t.TrackNum > 0 {
			idx = t.TrackNum
		}
		b.WriteString(fmt.Sprintf("  TRACK %02d AUDIO\n", idx))
		b.WriteString(fmt.Sprintf("    TITLE %q\n", t.Title))
		b.WriteString(fmt.Sprintf("    PERFORMER %q\n", t.Artist))
		if t.ISRC != "" {
			b.WriteString(fmt.Sprintf("    ISRC %s\n", t.ISRC))
		}
		b.WriteString("    INDEX 01 00:00:00\n")
	}

	filename := sanitizeFilename(config.Name) + ".cue"
	outputPath := filepath.Join(config.OutputDir, filename)
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("write CUE: %w", err)
	}
	return outputPath, nil
}

func GenerateNFO(config PlaylistConfig) (string, error) {
	var b strings.Builder
	b.WriteString("Generated by Bitly\n")
	b.WriteString(fmt.Sprintf("Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("Album: %s\n", config.Name))
	b.WriteString(fmt.Sprintf("Artist: %s\n", config.Artist))
	b.WriteString(fmt.Sprintf("Genre: %s\n", config.Genre))
	b.WriteString(fmt.Sprintf("Year: %s\n", config.Year))
	b.WriteString(fmt.Sprintf("Tracks: %d\n", len(config.Tracks)))
	b.WriteString("\n--- Track Listing ---\n")

	for i, t := range config.Tracks {
		dur := formatDuration(t.Duration / 1000)
		b.WriteString(fmt.Sprintf("%02d. %s - %s [%s]\n", i+1, t.Artist, t.Title, dur))
	}

	filename := sanitizeFilename(config.Name) + ".nfo"
	outputPath := filepath.Join(config.OutputDir, filename)
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		return "", fmt.Errorf("write NFO: %w", err)
	}
	return outputPath, nil
}

func GenerateBulkPlaylistFiles(config PlaylistConfig) []string {
	var generated []string

	if m3u, err := GenerateM3U(config); err == nil {
		generated = append(generated, m3u)
	}
	if m38, err := GenerateM3U8(config); err == nil {
		generated = append(generated, m38)
	}
	if cue, err := GenerateCUE(config); err == nil {
		generated = append(generated, cue)
	}
	if nfo, err := GenerateNFO(config); err == nil {
		generated = append(generated, nfo)
	}
	return generated
}

func formatDuration(seconds int) string {
	if seconds <= 0 {
		return "0:00"
	}
	m := seconds / 60
	s := seconds % 60
	return fmt.Sprintf("%d:%02d", m, s)
}
